import Link from 'next/link'
import React, { DOMAttributes } from 'react'
import { signIn, signOut, useSession } from "next-auth/react";
import Layout from '~/components/Layout'
import Head from 'next/head';


export default function Profile() {

  const {data: sessionData}=useSession()

  return (
    <>
    <Head>
        <title>Профиль</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
        <div className='mx-auto max-w-[1180px] p-4'>
          
          <p className="text-3xl">Профиль</p>
          <hr className="my-2 h-[7px] w-[300px] rounded bg-base" />

          <div className='flex flex-row gap-[200px] p-14 max-[860px]:flex-col'>
            <div className='flex flex-col gap-3'>
              <Link href="/profil"><p>Заказы</p></Link>
              <Link href="/profil"><p>Мои корзины</p></Link>
              <Link href="/profil"><p>Мои заказы</p></Link>
              <Link href="/profil"><p>Сравнения товаров</p></Link>
              <Link href="/profil"><p>Электронные чеки</p></Link>
              <br/>
              <Link href="/profil"><p>Баланс</p></Link>
              <Link href="/profil"><p>Мои карты</p></Link>
              <Link href="/profil"><p>Сохранённые карты</p></Link>
              <button 
              className='p-2 rounded text-white bg-red-600'
              onClick={()=>{sessionData? signOut() : signIn()}}>{sessionData? "Выход" : "Войти"}</button>
            </div>
            <div className='max-w-[400px] p-2 border-solid '>
                <p className="text-2xl">Мои финансы</p> 
                <div className='flex gap-[20px] flex-col justify-center shadow-xl p-5 rounded-xl items-center'>
                  <p className="text-2xl">Привяжите карту</p> 
                  <p className="text-xl">Оплачивайте свои покупки быстро и без подтвержеия смс</p> 
                  <button className='p-5 mt-2 rounded-xl bg-red-600 text-white '>Привязать</button>
                </div>
                <div className='max-w-[400px] mt-[40px] '>
                <p className="text-2xl">Активыные заказы</p> 
                <div className='bg-base w-[400px] rounded-xl shadow-xl h-[250px]'>
                  <p className='text-white p-5 text-xl font-basic'>На данный момент заказов нет</p>
                </div>
                </div>
            </div>
          </div>
        </div>

    </Layout>
    </>)
}
